import type { Business, Category, BusinessHours, Product, ServiceItem, Review, Promotion, BusinessWithDetails } from '@/types/database'

export const mockCategories: Category[] = [
  { id: '1', name: 'Alimentação', slug: 'alimentacao', icon: 'UtensilsCrossed', description: 'Restaurantes, lanchonetes, pizzarias e mais', parent_id: null, created_at: '2024-01-01' },
  { id: '2', name: 'Beleza & Estética', slug: 'beleza-estetica', icon: 'Sparkles', description: 'Salões, barbearias, clínicas de estética', parent_id: null, created_at: '2024-01-01' },
  { id: '3', name: 'Saúde', slug: 'saude', icon: 'Heart', description: 'Médicos, dentistas, fisioterapeutas', parent_id: null, created_at: '2024-01-01' },
  { id: '4', name: 'Moda & Vestuário', slug: 'moda-vestuario', icon: 'Shirt', description: 'Roupas, calçados, acessórios', parent_id: null, created_at: '2024-01-01' },
  { id: '5', name: 'Reparos & Manutenção', slug: 'reparos-manutencao', icon: 'Wrench', description: 'Eletricistas, encanadores, técnicos', parent_id: null, created_at: '2024-01-01' },
  { id: '6', name: 'Educação', slug: 'educacao', icon: 'GraduationCap', description: 'Escolas, cursos, aulas particulares', parent_id: null, created_at: '2024-01-01' },
  { id: '7', name: 'Tecnologia', slug: 'tecnologia', icon: 'Laptop', description: 'Informática, celulares, assistência técnica', parent_id: null, created_at: '2024-01-01' },
  { id: '8', name: 'Automotivo', slug: 'automotivo', icon: 'Car', description: 'Oficinas, autopeças, lava-jato', parent_id: null, created_at: '2024-01-01' },
  { id: '9', name: 'Casa & Decoração', slug: 'casa-decoracao', icon: 'Home', description: 'Móveis, decoração, materiais de construção', parent_id: null, created_at: '2024-01-01' },
  { id: '10', name: 'Esporte & Lazer', slug: 'esporte-lazer', icon: 'Dumbbell', description: 'Academias, esportes, entretenimento', parent_id: null, created_at: '2024-01-01' },
  { id: '11', name: 'Pet Shop & Veterinário', slug: 'pet-shop-veterinario', icon: 'PawPrint', description: 'Pets, banho e tosa, veterinários', parent_id: null, created_at: '2024-01-01' },
  { id: '12', name: 'Advocacia & Contabilidade', slug: 'advocacia-contabilidade', icon: 'Scale', description: 'Advogados, contadores, consultores', parent_id: null, created_at: '2024-01-01' },
]

const defaultHours: BusinessHours[] = [
  { id: '1', business_id: '1', day_of_week: 'monday', open_time: '08:00', close_time: '18:00', is_closed: false },
  { id: '2', business_id: '1', day_of_week: 'tuesday', open_time: '08:00', close_time: '18:00', is_closed: false },
  { id: '3', business_id: '1', day_of_week: 'wednesday', open_time: '08:00', close_time: '18:00', is_closed: false },
  { id: '4', business_id: '1', day_of_week: 'thursday', open_time: '08:00', close_time: '18:00', is_closed: false },
  { id: '5', business_id: '1', day_of_week: 'friday', open_time: '08:00', close_time: '18:00', is_closed: false },
  { id: '6', business_id: '1', day_of_week: 'saturday', open_time: '09:00', close_time: '13:00', is_closed: false },
  { id: '7', business_id: '1', day_of_week: 'sunday', open_time: '00:00', close_time: '00:00', is_closed: true },
]

export const mockBusinesses: BusinessWithDetails[] = [
  {
    id: '1',
    owner_id: 'user1',
    name: 'Restaurante Sabor da Terra',
    slug: 'restaurante-sabor-da-terra',
    type: 'store',
    description: 'O melhor da culinária caseira em Rio Bonito. Há mais de 15 anos servindo pratos feitos com ingredientes frescos e muito amor. Nosso buffet de almoço é referência na cidade, com mais de 30 opções diárias entre saladas, pratos quentes, grelhados e sobremesas.',
    short_description: 'Culinária caseira com buffet variado e pratos executivos',
    phone: '2126231234',
    whatsapp: '21999881234',
    email: 'contato@sabordaterra.com',
    website: null,
    instagram: '@sabordaterrarb',
    facebook: 'sabordaterrarb',
    address: 'Rua Dr. Ari Teixeira da Costa, 150 - Centro',
    neighborhood: 'Centro',
    city: 'Rio Bonito',
    state: 'RJ',
    zip_code: '28800-000',
    latitude: -22.7112,
    longitude: -42.6267,
    logo_url: null,
    cover_url: null,
    photos: [],
    subscription_plan: 'premium',
    subscription_status: 'active',
    subscription_expires_at: '2026-12-31',
    is_featured: true,
    is_verified: true,
    is_active: true,
    average_rating: 4.7,
    total_reviews: 48,
    created_at: '2024-01-15',
    updated_at: '2024-03-01',
    categories: [mockCategories[0]],
    hours: defaultHours,
    products: [
      { id: 'p1', business_id: '1', name: 'Buffet Almoço', description: 'Buffet livre com mais de 30 pratos', price: 34.90, promotional_price: 29.90, image_url: null, is_featured: true, is_active: true, sort_order: 1, created_at: '2024-01-15', updated_at: '2024-01-15' },
      { id: 'p2', business_id: '1', name: 'Prato Executivo', description: 'Arroz, feijão, salada e proteína', price: 22.90, promotional_price: null, image_url: null, is_featured: true, is_active: true, sort_order: 2, created_at: '2024-01-15', updated_at: '2024-01-15' },
      { id: 'p3', business_id: '1', name: 'Marmitex P', description: 'Marmita com arroz, feijão e 1 proteína', price: 15.00, promotional_price: null, image_url: null, is_featured: false, is_active: true, sort_order: 3, created_at: '2024-01-15', updated_at: '2024-01-15' },
    ],
    services: [],
    reviews: [
      { id: 'r1', business_id: '1', user_id: 'u1', user_name: 'Maria Silva', user_avatar: null, rating: 5, comment: 'Comida maravilhosa! Melhor buffet da cidade, sem dúvida.', reply: 'Obrigado, Maria! Volte sempre! 😊', replied_at: '2024-02-15', created_at: '2024-02-10' },
      { id: 'r2', business_id: '1', user_id: 'u2', user_name: 'João Santos', user_avatar: null, rating: 4, comment: 'Boa comida, preço justo. Só o estacionamento que é apertado.', reply: null, replied_at: null, created_at: '2024-02-20' },
    ],
    promotions: [
      { id: 'promo1', business_id: '1', title: '10% OFF no Buffet', description: 'Mencione o Catálogo Rio Bonito e ganhe 10% de desconto no buffet de almoço!', discount_type: 'percentage', discount_value: 10, coupon_code: 'CATALOGO10', starts_at: '2024-03-01', ends_at: '2026-12-31', is_active: true, created_at: '2024-03-01' },
    ],
  },
  {
    id: '2',
    owner_id: 'user2',
    name: 'Studio Beleza Pura',
    slug: 'studio-beleza-pura',
    type: 'service_provider',
    description: 'Salão de beleza completo com profissionais experientes e especializados. Oferecemos cortes modernos, colorações, tratamentos capilares, manicure, pedicure, design de sobrancelhas e maquiagem profissional. Ambiente climatizado e agradável.',
    short_description: 'Salão de beleza completo com profissionais especializados',
    phone: '2126235678',
    whatsapp: '21999885678',
    email: 'studio@belezapura.com',
    website: null,
    instagram: '@studiobelezapurarb',
    facebook: null,
    address: 'Rua Getúlio Vargas, 320 - Centro',
    neighborhood: 'Centro',
    city: 'Rio Bonito',
    state: 'RJ',
    zip_code: '28800-000',
    latitude: -22.7098,
    longitude: -42.6283,
    logo_url: null,
    cover_url: null,
    photos: [],
    subscription_plan: 'pro',
    subscription_status: 'active',
    subscription_expires_at: '2026-12-31',
    is_featured: true,
    is_verified: true,
    is_active: true,
    average_rating: 4.9,
    total_reviews: 72,
    created_at: '2024-01-10',
    updated_at: '2024-03-01',
    categories: [mockCategories[1]],
    hours: defaultHours.map(h => ({ ...h, business_id: '2' })),
    products: [],
    services: [
      { id: 's1', business_id: '2', name: 'Corte Feminino', description: 'Corte com lavagem e secagem', price: 60, duration_minutes: 45, image_url: null, is_featured: true, is_active: true, sort_order: 1, created_at: '2024-01-10', updated_at: '2024-01-10' },
      { id: 's2', business_id: '2', name: 'Coloração', description: 'Coloração completa com produtos premium', price: 120, duration_minutes: 90, image_url: null, is_featured: true, is_active: true, sort_order: 2, created_at: '2024-01-10', updated_at: '2024-01-10' },
      { id: 's3', business_id: '2', name: 'Manicure + Pedicure', description: 'Combo manicure e pedicure', price: 50, duration_minutes: 60, image_url: null, is_featured: true, is_active: true, sort_order: 3, created_at: '2024-01-10', updated_at: '2024-01-10' },
      { id: 's4', business_id: '2', name: 'Escova Progressiva', description: 'Alisamento com produtos de alta qualidade', price: 200, duration_minutes: 120, image_url: null, is_featured: false, is_active: true, sort_order: 4, created_at: '2024-01-10', updated_at: '2024-01-10' },
    ],
    reviews: [
      { id: 'r3', business_id: '2', user_id: 'u3', user_name: 'Ana Oliveira', user_avatar: null, rating: 5, comment: 'Melhor salão de Rio Bonito! A Carla é uma artista com as cores.', reply: 'Muito obrigada, Ana! Você arrasa! 💇‍♀️', replied_at: '2024-02-16', created_at: '2024-02-15' },
    ],
    promotions: [],
  },
  {
    id: '3',
    owner_id: 'user3',
    name: 'TechFix Assistência Técnica',
    slug: 'techfix-assistencia-tecnica',
    type: 'service_provider',
    description: 'Assistência técnica especializada em computadores, notebooks, celulares e tablets. Conserto rápido, peças originais e garantia em todos os serviços. Também fazemos formatação, upgrade e limpeza de vírus.',
    short_description: 'Assistência técnica para computadores e celulares',
    phone: '2126239012',
    whatsapp: '21999889012',
    email: 'techfix@email.com',
    website: null,
    instagram: '@techfixrb',
    facebook: null,
    address: 'Av. Presidente Lincoln, 88 - Centro',
    neighborhood: 'Centro',
    city: 'Rio Bonito',
    state: 'RJ',
    zip_code: '28800-000',
    latitude: -22.7105,
    longitude: -42.6290,
    logo_url: null,
    cover_url: null,
    photos: [],
    subscription_plan: 'basic',
    subscription_status: 'active',
    subscription_expires_at: '2026-12-31',
    is_featured: false,
    is_verified: true,
    is_active: true,
    average_rating: 4.5,
    total_reviews: 31,
    created_at: '2024-02-01',
    updated_at: '2024-03-01',
    categories: [mockCategories[6]],
    hours: defaultHours.map(h => ({ ...h, business_id: '3' })),
    products: [],
    services: [
      { id: 's5', business_id: '3', name: 'Formatação de Notebook', description: 'Formatação com backup e instalação de programas', price: 80, duration_minutes: 120, image_url: null, is_featured: true, is_active: true, sort_order: 1, created_at: '2024-02-01', updated_at: '2024-02-01' },
      { id: 's6', business_id: '3', name: 'Troca de Tela (Celular)', description: 'Substituição de tela original com garantia', price: 150, duration_minutes: 60, image_url: null, is_featured: true, is_active: true, sort_order: 2, created_at: '2024-02-01', updated_at: '2024-02-01' },
    ],
    reviews: [
      { id: 'r4', business_id: '3', user_id: 'u4', user_name: 'Carlos Mendes', user_avatar: null, rating: 5, comment: 'Consertou meu notebook em 1 dia! Excelente serviço.', reply: null, replied_at: null, created_at: '2024-02-25' },
    ],
    promotions: [],
  },
  {
    id: '4',
    owner_id: 'user4',
    name: 'Empório Sabores do Campo',
    slug: 'emporio-sabores-do-campo',
    type: 'store',
    description: 'Produtos naturais, orgânicos e artesanais direto do produtor rural. Frutas, legumes, queijos, geleias, pães artesanais e muito mais. Valorizando os produtores locais e a alimentação saudável.',
    short_description: 'Produtos naturais, orgânicos e artesanais',
    phone: '2126233456',
    whatsapp: '21999883456',
    email: null,
    website: null,
    instagram: '@emporiosaboresdocampo',
    facebook: 'emporiosaboresdocampo',
    address: 'Rua Nilo Peçanha, 205 - Centro',
    neighborhood: 'Centro',
    city: 'Rio Bonito',
    state: 'RJ',
    zip_code: '28800-000',
    latitude: -22.7120,
    longitude: -42.6275,
    logo_url: null,
    cover_url: null,
    photos: [],
    subscription_plan: 'premium',
    subscription_status: 'active',
    subscription_expires_at: '2026-12-31',
    is_featured: true,
    is_verified: true,
    is_active: true,
    average_rating: 4.8,
    total_reviews: 56,
    created_at: '2024-01-20',
    updated_at: '2024-03-01',
    categories: [mockCategories[0]],
    hours: defaultHours.map(h => ({ ...h, business_id: '4' })),
    products: [
      { id: 'p4', business_id: '4', name: 'Cesta Orgânica', description: 'Cesta semanal com frutas e verduras orgânicas', price: 89.90, promotional_price: null, image_url: null, is_featured: true, is_active: true, sort_order: 1, created_at: '2024-01-20', updated_at: '2024-01-20' },
      { id: 'p5', business_id: '4', name: 'Queijo Minas Artesanal', description: 'Queijo minas curado artesanal - 500g', price: 35.00, promotional_price: null, image_url: null, is_featured: true, is_active: true, sort_order: 2, created_at: '2024-01-20', updated_at: '2024-01-20' },
      { id: 'p6', business_id: '4', name: 'Geleia de Goiaba', description: 'Geleia caseira de goiaba - 300g', price: 18.00, promotional_price: 15.00, image_url: null, is_featured: false, is_active: true, sort_order: 3, created_at: '2024-01-20', updated_at: '2024-01-20' },
    ],
    services: [],
    reviews: [
      { id: 'r5', business_id: '4', user_id: 'u5', user_name: 'Patrícia Lima', user_avatar: null, rating: 5, comment: 'Produtos fresquíssimos! A cesta orgânica é incrível.', reply: 'Obrigado, Patrícia! Nossos produtores ficam felizes! 🌿', replied_at: '2024-02-20', created_at: '2024-02-18' },
    ],
    promotions: [
      { id: 'promo2', business_id: '4', title: 'Primeira Cesta com 15% OFF', description: 'Na sua primeira compra de cesta orgânica, ganhe 15% de desconto!', discount_type: 'percentage', discount_value: 15, coupon_code: 'PRIMEIRA15', starts_at: '2024-03-01', ends_at: '2026-12-31', is_active: true, created_at: '2024-03-01' },
    ],
  },
  {
    id: '5',
    owner_id: 'user5',
    name: 'Dr. Ricardo Almeida - Dentista',
    slug: 'dr-ricardo-almeida-dentista',
    type: 'service_provider',
    description: 'Odontologia geral, estética e implantes. Atendimento humanizado com tecnologia de ponta. Clareamento dental, lentes de contato, próteses e tratamento ortodôntico. Consultório moderno no coração de Rio Bonito.',
    short_description: 'Odontologia geral, estética e implantes dentários',
    phone: '2126237890',
    whatsapp: '21999887890',
    email: 'dr.ricardo@dentista.com',
    website: null,
    instagram: '@drricardodentista',
    facebook: null,
    address: 'Rua Dr. Ari Teixeira da Costa, 450 - Centro',
    neighborhood: 'Centro',
    city: 'Rio Bonito',
    state: 'RJ',
    zip_code: '28800-000',
    latitude: -22.7108,
    longitude: -42.6260,
    logo_url: null,
    cover_url: null,
    photos: [],
    subscription_plan: 'pro',
    subscription_status: 'active',
    subscription_expires_at: '2026-12-31',
    is_featured: true,
    is_verified: true,
    is_active: true,
    average_rating: 4.9,
    total_reviews: 89,
    created_at: '2024-01-05',
    updated_at: '2024-03-01',
    categories: [mockCategories[2]],
    hours: [
      { id: '1', business_id: '5', day_of_week: 'monday', open_time: '08:00', close_time: '17:00', is_closed: false },
      { id: '2', business_id: '5', day_of_week: 'tuesday', open_time: '08:00', close_time: '17:00', is_closed: false },
      { id: '3', business_id: '5', day_of_week: 'wednesday', open_time: '08:00', close_time: '17:00', is_closed: false },
      { id: '4', business_id: '5', day_of_week: 'thursday', open_time: '08:00', close_time: '17:00', is_closed: false },
      { id: '5', business_id: '5', day_of_week: 'friday', open_time: '08:00', close_time: '17:00', is_closed: false },
      { id: '6', business_id: '5', day_of_week: 'saturday', open_time: '08:00', close_time: '12:00', is_closed: false },
      { id: '7', business_id: '5', day_of_week: 'sunday', open_time: '00:00', close_time: '00:00', is_closed: true },
    ],
    products: [],
    services: [
      { id: 's7', business_id: '5', name: 'Consulta + Limpeza', description: 'Avaliação completa com limpeza e orientação', price: 120, duration_minutes: 40, image_url: null, is_featured: true, is_active: true, sort_order: 1, created_at: '2024-01-05', updated_at: '2024-01-05' },
      { id: 's8', business_id: '5', name: 'Clareamento Dental', description: 'Clareamento a laser em consultório', price: 800, duration_minutes: 60, image_url: null, is_featured: true, is_active: true, sort_order: 2, created_at: '2024-01-05', updated_at: '2024-01-05' },
      { id: 's9', business_id: '5', name: 'Extração Simples', description: 'Extração dentária com anestesia local', price: 150, duration_minutes: 30, image_url: null, is_featured: false, is_active: true, sort_order: 3, created_at: '2024-01-05', updated_at: '2024-01-05' },
    ],
    reviews: [
      { id: 'r6', business_id: '5', user_id: 'u6', user_name: 'Fernanda Costa', user_avatar: null, rating: 5, comment: 'Excelente profissional! Muito cuidadoso e atencioso. Super recomendo!', reply: 'Obrigado pela confiança, Fernanda! 😁', replied_at: '2024-02-22', created_at: '2024-02-21' },
    ],
    promotions: [],
  },
  {
    id: '6',
    owner_id: 'user6',
    name: 'Oficina do Seu Jorge',
    slug: 'oficina-do-seu-jorge',
    type: 'service_provider',
    description: 'Oficina mecânica com mais de 25 anos de experiência. Manutenção preventiva e corretiva, troca de óleo, alinhamento, balanceamento e diagnóstico computadorizado. Peças originais e garantia de serviço.',
    short_description: 'Mecânica automotiva com 25 anos de experiência',
    phone: '2126234567',
    whatsapp: '21999884567',
    email: null,
    website: null,
    instagram: null,
    facebook: 'oficinaseujorge',
    address: 'Rua Barão de Inoã, 580 - Mangueira',
    neighborhood: 'Mangueira',
    city: 'Rio Bonito',
    state: 'RJ',
    zip_code: '28800-000',
    latitude: -22.7135,
    longitude: -42.6240,
    logo_url: null,
    cover_url: null,
    photos: [],
    subscription_plan: 'basic',
    subscription_status: 'active',
    subscription_expires_at: '2026-12-31',
    is_featured: false,
    is_verified: true,
    is_active: true,
    average_rating: 4.6,
    total_reviews: 42,
    created_at: '2024-01-25',
    updated_at: '2024-03-01',
    categories: [mockCategories[7]],
    hours: defaultHours.map(h => ({ ...h, business_id: '6' })),
    products: [],
    services: [
      { id: 's10', business_id: '6', name: 'Troca de Óleo', description: 'Troca de óleo com filtro incluso', price: 120, duration_minutes: 30, image_url: null, is_featured: true, is_active: true, sort_order: 1, created_at: '2024-01-25', updated_at: '2024-01-25' },
      { id: 's11', business_id: '6', name: 'Alinhamento + Balanceamento', description: 'Alinhamento e balanceamento computadorizado', price: 100, duration_minutes: 60, image_url: null, is_featured: true, is_active: true, sort_order: 2, created_at: '2024-01-25', updated_at: '2024-01-25' },
    ],
    reviews: [
      { id: 'r7', business_id: '6', user_id: 'u7', user_name: 'Roberto Souza', user_avatar: null, rating: 5, comment: 'Seu Jorge é muito honesto e competente. Recomendo demais!', reply: null, replied_at: null, created_at: '2024-02-28' },
    ],
    promotions: [],
  },
]

export function getBusinessBySlug(slug: string): BusinessWithDetails | undefined {
  return mockBusinesses.find((b) => b.slug === slug)
}

export function getBusinessesByCategory(categorySlug: string): BusinessWithDetails[] {
  const category = mockCategories.find((c) => c.slug === categorySlug)
  if (!category) return []
  return mockBusinesses.filter((b) => b.categories.some((c) => c.id === category.id))
}

export function searchBusinesses(query: string): BusinessWithDetails[] {
  const q = query.toLowerCase()
  return mockBusinesses.filter(
    (b) =>
      b.name.toLowerCase().includes(q) ||
      b.description.toLowerCase().includes(q) ||
      b.categories.some((c) => c.name.toLowerCase().includes(q)) ||
      b.products.some((p) => p.name.toLowerCase().includes(q)) ||
      b.services.some((s) => s.name.toLowerCase().includes(q))
  )
}

export function getFeaturedBusinesses(): BusinessWithDetails[] {
  return mockBusinesses.filter((b) => b.is_featured)
}
